"""p2: pending_captures

Revision ID: 1313fe0b8ca8
Revises: 147f6ad29fed
Create Date: 2026-06-21 16:59:58.944449
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1313fe0b8ca8'
down_revision: Union[str, None] = '147f6ad29fed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_captures',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('chat_id', sa.String(length=64), nullable=False),
    sa.Column('transcript', sa.String(length=4000), nullable=False),
    sa.Column('draft', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pending_captures', schema=None) as batch_op:
        batch_op.create_index('ix_pending_user_status', ['user_id', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_captures', schema=None) as batch_op:
        batch_op.drop_index('ix_pending_user_status')

    op.drop_table('pending_captures')
    # ### end Alembic commands ###
